[project]
name = "qa-cross-domain-dataset"
version = "0.1.0"
description = "Cross-domain Question and Answer dataset"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.2",
]
